---
title: "Resultados de Experimentos de campo y en macetas"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(car)
library(tidyverse)

```

# Experimentos de campo 

## Data

```{r}
load("~/Dropbox/Papers/1 In progress/carbon_mani/data/field_data.RData")

dat %>% 
  filter(ai == "Check") %>% 
  group_by(year) %>% 
  summarise(min = min(x3.4/n_pods),
            max = max(x3.4/n_pods),
            mean = mean(x3.4/n_pods))
```

## Modelo 

### Considerando la interacción $a.i. * a\tilde{n}o$ 

```{r}
load("../data/field_model.rda")
plot(m)
Anova(m)
```
</br>
__Resultados 2015__

```{r}
res %>% 
  filter(year==2015) %>% 
  select(ai, prob, asymp.LCL, asymp.UCL, .group) %>%
  knitr::kable(digits = c(0, 0, 3, 3, 3, 0))
```
</br>
__Resultados 2016__

```{r}
res %>% 
  filter(year==2016) %>% 
  select(ai, prob, asymp.LCL, asymp.UCL, .group) %>%
  knitr::kable(digits = c(0, 0, 3, 3, 3, 0))
```

### Considerando a $a\tilde{n}o$ como efecto aditivo

```{r}
plot(m1)
Anova(m1)
```
</br>
__Resultados promediando a año para cada $a.i$__

```{r}
res1 %>% 
  select(ai, prob, asymp.LCL, asymp.UCL, .group) %>%
  knitr::kable(digits = c(3, 3, 3, 0))
```
