```{r, include=FALSE}
pacman::p_load(tidyverse, lubridate)
options(gargle_oauth_email = "edwardsmolina@gmail.com")
```

```{r}
meta_url <- "https://docs.google.com/spreadsheets/d/1-eCU4YfOiGz5Ox6RHX8CXDaQSUsmImEM_lQHAWtWybs/edit?usp=sharing"
metadata <- gsheet::gsheet2tbl(meta_url)  
id_trial <- "2019_tr_mad"
ensayos <- metadata %>% filter(id_ensayo == id_trial) 
```

```{r}
library(leaflet)
map_trials <- leaflet(ensayos) %>% 
  addTiles()  %>% 
  addMarkers(~-63.774969, ~-32.752718) %>% 
  setView(lng = -63.77, lat = -32.752718, zoom = 9)   

#Importar dataset
nasa <- nasapower::get_power(
  community = "AG",
  lonlat = c(-63.774969, -32.752718),
  pars = c( "T2M_MIN", "T2M_MAX","ALLSKY_SFC_SW_DWN", "PRECTOT"),
  dates = c("2014-01-01", "2016-12-31"),
  temporal_average = "DAILY"
)
```

```{r}
fototerm <- nasa %>%  
  filter(ALLSKY_SFC_SW_DWN>0, 
         MM %in% 6:12) %>% 
  mutate(julian= yday(YYYYMMDD),  
         tmean =  (T2M_MAX + T2M_MIN)/2,
         pq = ALLSKY_SFC_SW_DWN/(tmean-4.5)) 
# nasa %>%   
#   filter(ALLSKY_SFC_SW_DWN>0) %>% 
#   mutate(julian= yday(YYYYMMDD)) %>% 
#   ggplot(aes(x = julian, y = ALLSKY_SFC_SW_DWN))+
#   geom_line() + 
#   facet_wrap(~YEAR)
```

```{r}
# Calcular percentiles para cada dia juliano
fototerm_serie <- 
  fototerm %>% 
  filter(YEAR<2019) %>% 
  group_by(julian) %>% 
  summarise(
    t10=quantile(tmean, .1, na.rm = T), 
    t50=quantile(tmean, .5, na.rm = T), 
    t90=quantile(tmean, .9, na.rm = T), 
    pq10 = quantile(pq, .1, na.rm = T),
    pq50 = quantile(pq, .5, na.rm = T),
    pq90 = quantile(pq, .9, na.rm = T), 
    rad10 = quantile(ALLSKY_SFC_SW_DWN, .1, na.rm = T),
    rad50 = quantile(ALLSKY_SFC_SW_DWN, .5, na.rm = T),
    rad90 = quantile(ALLSKY_SFC_SW_DWN, .9, na.rm = T))
```

```{r}
fototerm_season <- 
  fototerm %>% 
  # mutate(julian= yday(YYYYMMDD)) %>% 
  filter(ALLSKY_SFC_SW_DWN>0) %>% 
  filter(YEAR==2019, MM %in% 6:12) 
```

```{r}
fototerm1 <- # fusionar ambos datasets (serie + campaña)
  fototerm_season %>%
  left_join(fototerm_serie, by = "julian") 
```


```{r}
cowplot::plot_grid(ncol = 1,

fototerm1 %>% 
  ggplot(aes(x = YYYYMMDD, y = ALLSKY_SFC_SW_DWN))+
  geom_linerange(aes(ymin = rad10, ymax = rad90), col="grey70")+
  geom_smooth()+
  labs(x="", y="Radiación global")
,

fototerm1 %>% 
  ggplot(aes(x = YYYYMMDD, y =  (T2M_MAX + T2M_MIN)/2))+
  geom_line(aes(y=t50))+
  geom_linerange(aes(ymin = t10, ymax = t90), col="grey70")+
  geom_smooth(se=F)+
  labs(x="", y="Temp. media (C°)")
,

fototerm %>% 
  ggplot(aes(x = YYYYMMDD, y =pq))+
  # geom_smooth(se=T)+
  geom_linerange(aes(ymin = pq10, ymax = pq90), col="grey70")+
  labs(x="", y="Cociente fototermal")
)
```


```{r}
fototerm %>%   
  filter(YEAR<2019) %>% 
  ggplot(aes(x = julian, y =ALLSKY_SFC_SW_DWN))+
  geom_quantile(quantiles=0.5, method = "rqss", col="grey30")+
  geom_line(data =  fototerm_serie, aes(x=julian, y = rad50), col = "green") + 
  # geom_line(data =fototerm %>% filter(YEAR==2019),col = "blue",
  #           aes(x = julian, y =ALLSKY_SFC_SW_DWN))+
  geom_quantile(data =fototerm %>% filter(YEAR==2019) , 
            aes(x=julian, y = ALLSKY_SFC_SW_DWN),
            quantiles=0.5, method = "rqss", col="red")+
  # geom_linerange(aes(ymin = pq10, ymax = pq90), col="grey70")+
  labs(x="", y="Cociente fototermal")
)
```


```{r}
rain_serie <- 
  nasa %>%
  filter(YEAR<2019, MM %in% 6:12) %>% 
  mutate(mes = month(YYYYMMDD)) %>% 
  group_by(YEAR, mes) %>%
  # date = if_else(day(date) >= 30,
  #                floor_date(date, "20 days"),
  #                floor_date(date, "10 days")),
  summarize(rain_acum = sum(PRECTOT), 
            tmin=mean(T2M_MIN), 
            tmax=mean(T2M_MAX)) %>% ungroup %>%
  group_by(mes) %>%
  summarise(#MM = first(MM),
            rain_med = quantile(rain_acum, .5, na.rm = T),
            rain_20=quantile(rain_acum, .2, na.rm = T), 
            rain_80=quantile(rain_acum, .8, na.rm = T), 
            tmin=mean(tmin), 
            tmax=mean(tmax)) %>% 
  ungroup %>% 
  mutate(mes = month(as.data(mes))) 

```

```{r}
rain_season <- 
  nasa %>%
  filter(YEAR==2019, MM %in% 6:12) %>% 
  mutate(T2M_MEAN = T2M_MAX-T2M_MIN) %>% 
  group_by(MM) %>%
  summarise(#MM = first(MM),
            rain_acum = sum(PRECTOT),
            tmean = mean(T2M_MEAN),
            tmin=mean(T2M_MIN), 
            tmax=mean(T2M_MAX))
```
  
```{r}
(p1 <-
    nasa_serie %>%
    ggplot(aes(x=month(MM))) +
    geom_pointrange(aes(y=rain_med, ymin=rain_20, ymax=rain_80), 
                    fill='white', color='deepskyblue',
                    shape=21, fatten=.7, size=3, position=(p5=position_nudge(x = 5)))+
    geom_point(data= nasa_season, 
    aes(x=MM, y=rain_acum), col ="brown1", position=p5) +
    geom_line(data= nasa_season, aes(y=rain_acum, group=1), col ="brown1", linetype="dashed", position=p5)+
    # <!-- scale_y_continuous( breaks = function(x) unique( floor(pretty(seq(0, (max(x) + 1) * 1.1)))))+ -->
    scale_x_date(date_breaks="1 month", date_labels="%b", expand=expand(0.05,0))
)

```


```{r}
group_by(MM) %>%
  # mutate(decada = row_number()) %>%
  ggplot(aes(mes, rain_acum, fill=fuente))+ #rainy_days
  geom_col(alpha=0.5) +
  # facet_wrap(~fuente, ncol=1)+
  scale_x_continuous(breaks=seq(1,36,by=1))+
  scale_y_continuous( breaks = function(x) unique( floor(pretty(seq(0, (max(x) + 1) * 1.1)))))+
  theme_bw()+
  labs(y="lluvias acum (mm)")+
  labs(y="dias con al menos 3 mm")+
  guides(x = guide_axis(angle = 90))
```

```{r}
save(list=ls(), file="meteo_report.Rda")
```
