---
title: "multivar"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pacman::p_load(tidyverse, FactoMineR, factoextra)
```

## Data

```{r}
dat <- tibble::tribble(
            ~fungicide, ~in_vitro, ~pot_2015, ~pot_2016, ~field_2015, ~field_2016,
        "Azoxystrobin",      0.01,      58.9,        92,        47.7,        39.5,
      "Chlorothalonil",      0.18,     30.12,         0,        37.2,        12.2,
       "Cyproconazole",      0.03,      23.3,        82,        25.8,        20.9,
      "Difenoconazole",         0,      41.1,        42,        20.7,        13.3,
     "Kresoxim-Methyl",      0.22,      17.8,        36,        18.9,         9.9,
            "Mancozeb",      6.28,        11,        44,        17.9,          12,
        "Penthiopyrad",      0.02,       1.4,        14,        16.8,         7.8,
       "Picoxystrobin",      0.11,        26,        62,        16.6,        13.8,
       "Propiconazole",         0,       2.7,        46,        11.7,        23.7,
      "Pyraclostrobin",      0.02,       8.2,        22,         8.2,         3.2,
        "Tebuconazole",      0.01,      30.1,        74,         7.4,           0,
  "Thiophanate-Methyl",       100,        11,         0,         4.8,        12.4
  ) %>%
  column_to_rownames(var = "fungicide")
```

PCA [guia](http://www.sthda.com/english/articles/31-principal-component-methods-in-r-practical-guide/112-pca-principal-component-analysis-essentials/)

```{r}
res.pca <- PCA(dat, scale.unit = TRUE, ncp = 5, graph = F)
res.pca$var
res.pca$ind
res.pca$eig
```

```{r}
p1 <- fviz_pca_biplot(res.pca, 
                      arrowsize = 0.5,
                      repel = TRUE, 
                      title = "", 
                      col.ind = "grey10", # Variables color
                      col.var = "grey50"  # Individuals color
)
p1

# ggsave(p1, filename = "biplot_fungicide.png", dpi = 300)
```

